#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration
# displays Best School and then Hi on a new line
ndx=0
while [ $ndx -lt 11 ]
do
	if [ $ndx -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((ndx++))
done
