#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and displays:
# 4 and then bad luck from China for the 4th loop iteration
# 9 and then bad luck from Japan for the 9th loop iteration
# 17 and then bad luck from Italy for the 17th loop iteration
ndx=1
while [ $ndx -le 20 ]
do
	case $ndx in
		4)
			echo "$ndx"
			echo "bad luck from China"
			;;
		9)
			echo "$ndx"
			echo "bad luck from Japan"
			;;
		17)
			echo "$ndx"
			echo "bad luck from Italy"
			;;
		*)
			echo $ndx
			;;
	esac
	((ndx++))
done
