#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory in list format
for file in *
do
	if [ -f "$file" ] && [[ "$file" == *-* ]]
	then
		IFS='-' read -ra parts <<< "$file"
		echo "${parts[@]:1}"
	fi
done
